### ISSUE TITLE
Split up into multiple configs

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/tslint-config-shopify#14]
As per @GoodForOneFare's [comment](https://github.com/Shopify/tslint-config-shopify/pull/12/files/0436610c94f91be3ea66a6b7abb2d3ba3c543369#diff-168726dbe96b3ce427e7fedce31bb0bc)

https://palantir.github.io/tslint/2016/03/31/sharable-configurations-rules.html

**Comment by GoodForOneFare** [comment]
Per [this discussion](https://github.com/Shopify/sewing-kit/pull/5), we should have something like:
* `tslint-config-shopify/base`
* `tslint-config-shopify/typed`

This should reduce project boilerplate a little.
