### ISSUE TITLE
Missing no-unused-variable

### ISSUE THREAD

**Issue by lemonmade** [Shopify/tslint-config-shopify#19]
https://palantir.github.io/tslint/rules/no-unused-variable/ doesn't seem to be part of the config. Are we sure we have all the rules configured?

cc/ @GoodForOneFare @ismail-syed

**Comment by ismail-syed** [comment]
I'm pretty sure it's been [deprecated](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v400-dev1)

I remember the initial run with `tslint` it was shouting about some rule being `deprecated`. I believe it's this one. They probably just didn't update their website docs.

**Comment by lemonmade** [comment]
Welp, OK. I guess we need to turn on those flags for TS then.
