### ISSUE TITLE
Flag unbound method references

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/tslint-config-shopify#41]
Like [no-unbound-method](https://palantir.github.io/tslint/rules/no-unbound-method/) on steroids:
* Flag an unbound method reference, i.e., `requestAnimationFrame(this.bar)`
* ... if it is *not* bound in a constructor
* ... *and* it is *not* annotated with `@autobind`

This is fine:
```js
class Foo { 
  constructor() {
    this.bar = this.bar.bind(this);
  }

  bar() {}

  qux() {
    requestAnimationFrame(this.bar); // this.bar was bound in the constructor; all good!
  }
}
```

This is fine:
```js
class Foo { 
  constructor() {
  }

  @autobind // 
  bar() {}

  qux() {
    requestAnimationFrame(this.bar); // this.bar was autobound; all good!
  }
}
```

This is bad:
```js
class Foo { 
  constructor() {
  }

  bar() {}

  qux() {
    requestAnimationFrame(this.bar); // no constrcutor binding; no autobind; bad!
  }
}
```

**Comment by GoodForOneFare** [comment]
@lemonmade would this rule be useful?  Can we just enforce `@autobind` everywhere?

**Comment by lemonmade** [comment]
I think it's not universally applicable. It is never needed for React lifecycle hooks (most notably, render), and not needed if a function actually doesn't use `this` (unlikely and undesirable, but occasionally needed), and not needed for methods that are never passed as callbacks. IMO, too many potential issues to make it a rule.
