### ISSUE TITLE
Add 2 spaces to indent rule

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/tslint-config-shopify#67]

**Comment by GoodForOneFare** [comment]
Fixed by https://github.com/Shopify/tslint-config-shopify/pull/64

**Comment by ismail-syed** [comment]
Meant for updating our [`indent`](https://github.com/Shopify/tslint-config-shopify/blob/b3004f395ad48a4906ecbf99f80e45899f15a17d/src/rules/maintainability.ts#L11) config option

See https://palantir.github.io/tslint/rules/indent/
